# Generated by Django 5.0.3 on 2024-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_about_service_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
