# Generated by Django 4.2.11 on 2024-05-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_vetptofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetCategory',
            new_name='Pet',
        ),
    ]
