# Generated by Django 4.2.11 on 2024-05-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='available',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='price',
        ),
    ]
