# Generated by Django 4.2.11 on 2024-05-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_remove_pet_available_remove_pet_best_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='has_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='I want to make an appointment'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('US', 'American Region'), ('IN', 'Indian Region'), ('CN', 'Chinese Region')], max_length=10),
        ),
    ]
