# Generated by Django 4.2.11 on 2024-05-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_appointment_vet_pet_age_pet_breed_pet_has_vaccinated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('experience', models.IntegerField(default=1)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vetprofile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.departments')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='vetptofile',
        ),
    ]
