# Generated by Django 4.2.11 on 2024-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_vetprofile_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
